import { defineConfig } from "vitest/config";
import react from "@vitejs/plugin-react";
import path from "path";

export default defineConfig({
  plugins: [react()],
  test: {
    environment: "jsdom",
    setupFiles: ["./src/test/setup.ts"],
    globals: true,
    exclude: ["**/node_modules/**", "**/e2e/**"],
    coverage: {
      provider: "v8",
      reporter: ["text", "json", "html", "lcov", "clover"],
      reportsDirectory: "./coverage",
      all: true,
      include: ["src/**/*.{ts,tsx}"],
      exclude: [
        "**/node_modules/**",
        "**/e2e/**",
        "**/*.test.ts",
        "**/*.test.tsx",
        "**/*.spec.ts",
        "**/*.d.ts",
        "src/test/**",
        "src/app/**",
        "src/actions/**",
        "src/proxy.ts",
        "src/components/WebVitals.tsx",
        "src/middleware.ts",
        "src/data/**",
        "src/i18n/**",
        "src/types/calendar.ts",
        "src/types/locale.ts",
        "src/types/portfolio.ts",
        "src/types/email/**",
        "src/types/newsletter/**",
        "src/types/services/**",
        "src/hooks/useNotificationSound.ts",
        "src/hooks/useDesktopNotifications.ts",
        "src/components/dashboard/**",
        "src/components/settings/**",
        "src/components/email/**",
        "src/components/about/**",
        "src/components/activity/**",
        "src/components/calendar/**",
        "src/components/services/**",
        "src/components/resume/**",
        "src/components/legal/**",
        "src/components/testimonials/**",
        "src/components/notifications/**",
        "src/components/blog/BlogContent.tsx",
        "src/components/newsletter/editor/**",
        "src/components/newsletter/shared/**",
        "src/components/newsletter/forms/NewsletterProvider.tsx",
        "src/components/contact/BookingSection.tsx",
        "src/components/contact/ContactInfo.tsx",
        "src/components/home/LatestArticles.tsx",
        "src/components/home/NewsletterSection.tsx",
        "src/components/newsletter/forms/PopupModal.tsx",
        "src/components/shared/AnimateOnScroll.tsx",
        "src/components/shared/JsonLd.tsx",
        "src/lib/activity-wrappers.ts",
        "src/lib/ai/rag.ts",
        "src/lib/chatbot/analytics.ts",
        "src/lib/cron/reminder-processor.ts",
        "src/lib/email/brevo.ts",
        "src/lib/rate-limit.ts",
        "src/lib/resume-pdf/corporate.tsx",
        "src/lib/resume-pdf/developer.tsx",
        "src/lib/resume-pdf/executive.tsx",
        "src/lib/resume-pdf/minimalist.tsx",
        "src/lib/resume-pdf/modern.tsx",
        "src/lib/uploadthing.ts",
        "src/components/ui/badge.tsx",
        "src/components/ui/button.tsx",
        "src/components/ui/card.tsx",
        "src/components/ui/checkbox.tsx",
        "src/components/ui/dialog.tsx",
        "src/components/ui/input.tsx",
        "src/components/ui/label.tsx",
        "src/components/ui/select.tsx",
        "src/components/ui/sonner.tsx",
        "src/components/ui/switch.tsx",
        "src/components/ui/textarea.tsx",
        "src/components/ui/toast.tsx",
        "src/components/ui/skeleton.tsx",
        "src/components/ui/CalendlyEmbed.tsx",
        "src/components/ui/FriendlyEmbed.tsx",
        "src/components/ui/ImageSwitcher.tsx",
        "src/components/ui/ImageUpload.tsx",
        "src/components/ui/LanguageSwitcher.tsx",
        "src/components/ui/Lightbox.tsx",
        "src/components/ui/LocaleProvider.tsx",
        "src/components/ui/ScrollManager.tsx",
        "src/components/ui/ScrollManagerWrapper.tsx",
        "src/components/ui/newsletter/**",
        "src/components/GoogleAnalytics.tsx",
        "src/components/layout/LayoutWrapper.tsx",
        "src/components/chat/index.ts",
        "src/components/home/HomepageDataProvider.tsx",
        "src/components/home/HomeTestimonialsClient.tsx",
        "src/lib/brevo/types.ts",
        "src/lib/notifications/index.ts",
        "src/lib/uploadthing-client.ts",
      ],
      thresholds: {
        lines: 80,
        branches: 80,
        functions: 80,
        statements: 80,
        perFile: true,
      },
    },
  },
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
});
